### ISSUE TITLE
[EBOOK]Need changelog Information for latest Ebook Content

### ISSUE THREAD

**Issue by consciousnessdev** [novalagung/dasarpemrogramangolang#45] opened 2020-04-19 00:40 UTC
Before i learn from ebook which contain 255pages(i don't know a date version :X), then now i'd check on web pages https://dasarpemrogramangolang.novalagung.com/ , then i'd downloaded, i see page quantity has grown to 558, and my learning progress which is on page 58 with title "Alokasi Elemen Array Menggunakan Keyword make", shrinking to page 52.

I need information of what change in latest ebook, thanks

**Comment by novalagung** [comment] 2020-04-19 01:29
this will be hard for me. because the change was made years ago.

@consciousnessdev can you help?

**Comment by novalagung** [comment] 2020-04-19 01:30
to see the changes, we can do some checkin in the commit logs

**Comment by novalagung** [comment] 2020-04-20 22:39
I think even we already got the list of the changelogs, there will no improvement whatsoever to this ebook it self. and also I can confirm that the changes happened to improve the quality of the content (not just the quantity), so rest assured.

I'm closing this issue, thanks.

**Closed by novalagung** 2020-04-20 22:39 UTC
Labels: help wanted
